version: '3.7'
services:
    postgres:
        image: postgres:13.7-alpine3.16
        container_name: postgres
        restart: "no"
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - '5438:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
